template = ""
rev_id = 150
template_sha = "63eb1e7f5532c9d35870c9621ecf9fb2774c87dd"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
