template = ""
rev_id = 144
template_sha = "87383add18653dc7608e5e1bb7df4ebf29e326ca"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
