template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "maku1246"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
