template = ""
rev_id = 113
template_sha = "4c8956bd71a583d79116b749e3ce61710e8fa415"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
