template = ""
rev_id = 75
template_sha = "3632636146f363f95b04c7b5ec97661cf508ab68"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xak"
__UND2C__ = "xak"
__UNDEFINED__ = "Maku"
__UND__ = "xak"
